2024/04/10 上課內容：類別、物件導向以及Python模組介紹頁面


## 類別

就是class

In [ ]:
L = [1,2,3]
print(type(L)) # 注意一下最前面的關鍵字

<class 'list'>


自己創建一個類別，假設我們想要處理一個群的問題，然後這個群有它的元素，以及它自己的加法

In [ ]:
def add(a,b,p):       # 函數
  return (a+b) % p    # 計算a+b除以p的餘數


class Operator:       # 定義一個類別(class)
  def __init__(self, opname, op): # 類別一開始產生的時候，會有的東西
    self.name = opname      # name 自已定義的，要有什麼tag都可以
    self.fun = op         # fun 自己定義的，

ADD = Operator("Add mod prime", add)  # 把ADD定義成一個Operator的類別，其中的函數是add

print(type(add))
print(isinstance(ADD,Operator))
print(ADD.__class__)
print(type(L))

def mul(a,b,p):         # 乘法函數
  return (a*b) % p

MUL = Operator("Multiply mod prime", mul) # 把MUL定義成一個Operator的類別，其中的函數是mul


<class 'function'>
True
<class '__main__.Operator'>
<class 'list'>


再把運算子包在另一個類別中

In [ ]:
class Group:                  # 群-->大二代數課
  def __init__(self, group_name, op, prime):
    self.group_name = group_name
    self.op = op
    self.prime = prime
    self.elements = list(range(0,prime))
    self.identity = None

  def info(self):
    print(f"Group name: {self.group_name}")
    print(f"Elements: {self.elements} with {self.op.name} {self.prime}")
    if self.identity == None:
      self.find_identity()
    print(f"Identity: {self.identity}")

  def op_table(self,op=None):   # optional input
    if op == None:
      op = self.op
    print(f"Operator: {op.name}")
    for a in self.elements:
      c = []
      for b in self.elements:
        c.append(op.fun(a,b,self.prime))  # c = a+b
      print(c)

  def find_identity(self,op=None):
    if op == None:
      op = self.op
    for x in self.elements:
      identity = True
      for y in self.elements:
        if op.fun(x,y,self.prime) != y:
          identity = False
      if identity:
        self.identity = x

Z5 = Group("Z5", ADD, 5) # --> 執行 __init__(Z5, "Z5", ADD, 5)
Z5.info()
Z7 = Group("Z7", MUL, 7)
Z7.info()
Z7.op_table()

Group name: Z5
Elements: [0, 1, 2, 3, 4] with Add mod prime 5
Identity: 0
Group name: Z7
Elements: [0, 1, 2, 3, 4, 5, 6] with Multiply mod prime 7
Identity: 1
Operator: Multiply mod prime
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6]
[0, 2, 4, 6, 1, 3, 5]
[0, 3, 6, 2, 5, 1, 4]
[0, 4, 1, 5, 2, 6, 3]
[0, 5, 3, 1, 6, 4, 2]
[0, 6, 5, 4, 3, 2, 1]


## 繼承

如果其他的類別，還要之前設定類別的功能，就用繼承。舉例來說，一個Ring一定要有一個Group的結構
(這個等到大二代數課你們再去了解吧 XDDDDD)

In [ ]:
def mul(a,b,p):
  return (a*b) % p

MUL = Operator("Multiply mod prime", mul)

class Ring(Group):        # Ring 是一個繼承 Group 的類別
  def __init__(self, ring_name, op1, op2, prime):
    super().__init__(ring_name+"的爸爸", op1, prime) # 寫完這一行，代表Ring也是一個op1, prime的Group，繼承了Group的prime跟op
    self.ring_name = ring_name
    self.op2 = op2
    #self.op = op1 這個就不用寫了
    #self.prime = prime 這個也不用寫了

  def info(self):
    super().info()  # 如果下面沒寫，這一行不用寫也是同一個情況，因為它繼承了Group的info
    print(f"and operator {self.op2.name} {self.prime}")

  def op_table(self):
    super().op_table()
    super().op_table(self.op2)

# 創建一個
R5 = Ring("R5", ADD, MUL, 5)
R5.info()
R5.op_table()
#R5.all_table()


Group name: R5的爸爸
Elements: [0, 1, 2, 3, 4] with Add mod prime 5
Identity: 0
and operator Multiply mod prime 5
Operator: Add mod prime
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 0]
[2, 3, 4, 0, 1]
[3, 4, 0, 1, 2]
[4, 0, 1, 2, 3]
Operator: Multiply mod prime
[0, 0, 0, 0, 0]
[0, 1, 2, 3, 4]
[0, 2, 4, 1, 3]
[0, 3, 1, 4, 2]
[0, 4, 3, 2, 1]


# 模組

當你覺得你寫的函數，物件，類別多到可以處理一些事情了，你可以把它放在一個.py檔案裡面，透過 import 的方式讀進來

In [ ]:
import mygroup   # 就是把mygroup.py 執行過一次

YA


In [ ]:
mygroup.add(2,8,7)

U5 = mygroup.Group("Integer mod 5", MUL, 5)
U5.info()

Group name: Integer mod 5
Elements: [0, 1, 2, 3, 4] with Multiply mod prime 5
Identity: 1


In [ ]:
import mygroup as mg   # 取一個好用的名字

print(mg.Operators["MUL"].fun(2,3,5))

Z7 = mg.Z(7)
Z7.info()
Z7.all_table()

1
Group name: Z7
Elements: [0, 1, 2, 3, 4, 5, 6] with Add mod prime 7
Identity: 0
and operator Multiply mod prime 7
Operator: Add mod prime
[0, 1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 0]
[2, 3, 4, 5, 6, 0, 1]
[3, 4, 5, 6, 0, 1, 2]
[4, 5, 6, 0, 1, 2, 3]
[5, 6, 0, 1, 2, 3, 4]
[6, 0, 1, 2, 3, 4, 5]
Operator: Multiply mod prime
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6]
[0, 2, 4, 6, 1, 3, 5]
[0, 3, 6, 2, 5, 1, 4]
[0, 4, 1, 5, 2, 6, 3]
[0, 5, 3, 1, 6, 4, 2]
[0, 6, 5, 4, 3, 2, 1]


所以，下面的程式，就是在跟你說，someone寫了一個sys.py放在python可以找到module的地方，然後裡面有一個path的變數

我們把它印出來，然後增加一個 '/content/mylib'

這樣python就會找mylib中的py檔案了

In [ ]:
import sys
print(sys.path)

sys.path.append('/content/mylib')


['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython']


好吧，那接下來的任務，就是交給你們自己去找module，然後拿進來用了。

In [ ]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]])

result = np.dot(matrix1, matrix2)
print("Matrix Multiplication:")
print(result)


Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import sympy as sy

# 定义符号变量
x, y = sy.symbols('x y')

# 定义表达式
expr = x*x + 2*x + 1
print("Expression:", expr)

eq = x**3 - 5
solution = sy.solve(eq, x)
print(solution)

In [ ]:
class Group:
    def __init__(self, elements, operation):
        self.elements = elements  # 群的元素
        self.operation = operation  # 群的二元运算

    def is_closed(self):
        for a in self.elements:
            for b in self.elements:
                if self.operation(a, b) not in self.elements:
                    return False
        return True

    def is_associative(self):
        for a in self.elements:
            for b in self.elements:
                for c in self.elements:
                    if self.operation(self.operation(a, b), c) != self.operation(a, self.operation(b, c)):
                        return False
        return True

    def has_identity(self):
        for a in self.elements:
            has_identity = False
            for b in self.elements:
                if self.operation(a, b) == b and self.operation(b, a) == b:
                    has_identity = True
            if not has_identity:
                return False
        return True

    def has_inverses(self):
        for a in self.elements:
            has_inverse = False
            for b in self.elements:
                if self.operation(a, b) == self.operation(b, a):
                    has_inverse = True
            if not has_inverse:
                return False
        return True


# 示例：整数加法群
def addition(a, b):
    return a + b

integer_set = {0, 1, 2, 3, 4}
integer_addition_group = Group(integer_set, addition)

print("Closure:", integer_addition_group.is_closed())
print("Associativity:", integer_addition_group.is_associative())
print("Identity:", integer_addition_group.has_identity())
print("Inverses:", integer_addition_group.has_inverses())


Closure: False
Associativity: True
Identity: False
Inverses: True


# 作業

以下就是"下"星期五要交的工作
1. 自己寫一個程式，可以讓Group產生時，自己定義一個elements的list，然後檢查這個list裡面的任兩個元素經過op的函數之後，是不是都落在這個list裡面，如果是的話，就印出它滿足封閉性，如果不是就印出哪兩個元素算出來之後沒有落在這個list裡面(進階問題：對於每一個元素a，要找出它的反元素b，它會滿足 op(a,b,p) = 單位元素) 請參照: https://zh.wikipedia.org/zh-tw/%E7%BE%A4
2. 透過 import numpy as np，寫一些跟矩陣相關的運算
3. 透過 import sympy as sy，寫一些跟符號運算相關的計算


(類似的考題: 請把一個list，運算函數，跟一個質數p放在一個類別中，並在類別中定義一個函數，檢查op(a,(b○c))==(op((a○b),c))

以下是第一題的答案

In [43]:
class Group:
    def __init__(self, elements, operation):
        self.elements = elements 
        self.operation = operation 

    def is_closed(self):
        for a in self.elements:
            for b in self.elements:
                if self.operation(a, b) not in self.elements:
                    return False
        return True

    def is_associative(self):
        for a in self.elements:
            for b in self.elements:
                for c in self.elements:
                    if self.operation(self.operation(a, b), c) != self.operation(a, self.operation(b, c)):
                        return False
        return True

    def has_identity(self):
        for a in self.elements:
            has_identity = False
            for b in self.elements:
                if self.operation(a, b) == b and self.operation(b, a) == b:
                    has_identity = True
            if not has_identity:
                return False
        return True

    def has_inverses(self):
        for a in self.elements:
            has_inverse = False
            for b in self.elements:
                if self.operation(a, b) == self.operation(b, a):
                    has_inverse = True
            if not has_inverse:
                return False
        return True
    

table=[[0]*11 for i in range(11)]

def op(a,b) :
    return (a*b+10)%10

element_list = []
for i in range(11) :
    element_list.append(i)

for i in element_list :
    for j in element_list :
        table[i][j] = op(i,j)

for i in table :
    print(i)

group = Group(element_list , op )

print("Closure:", group.is_closed())
print("Associativity:", group.is_associative())
print("Identity:", group.has_identity())
print("Inverses:", group.has_inverses())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0]
[0, 3, 6, 9, 2, 5, 8, 1, 4, 7, 0]
[0, 4, 8, 2, 6, 0, 4, 8, 2, 6, 0]
[0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0]
[0, 6, 2, 8, 4, 0, 6, 2, 8, 4, 0]
[0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0]
[0, 8, 6, 4, 2, 0, 8, 6, 4, 2, 0]
[0, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Closure: True
Associativity: True
Identity: True
Inverses: True


以下是第二題的答案

In [ ]:
import numpy as np

a = np.matrix([[2,-1,2],[-1,3,-1],[2,-1,4]])
b = np.matrix([[2,1,0],[1,0,-1],[0,1,4]])

check_a = True
for i in range(1,4) :
    submatrix = a[:i,:i]
    if np.linalg.det(submatrix) <= 0 :
        check_a = False

check_b = True
for i in range(1,4) :
    submatrix = b[:i,:i]
    if np.linalg.det(submatrix) <= 0 :
        check_b = False
        break


if check_a : print("a is Positive definite")
else : print("a is not Positive definite")

if check_b : print("b is Positive definite")
else : print("b is not Positive definite")

以下是第三題的答案

In [ ]:
import sympy as sy

x = sy.symbols('x')
y = sy.symbols('y')


print( sy.expand( (x+y)**2 - (x-y)**2 ) )

print( sy.expand( (x-1)*(x-2)*(x-3)*(x-4) ) )

print( sy.factor( x**4-1 ) )

print( sy.limit( (x**2-4)/(x**3 -2*x**2 +2*x -4) , x, 2 ) )